
cluster.name: "docker-cluster"
network.host: 0.0.0.0
node.name: "es_master"
node.master: true
node.data: true
bootstrap.memory_lock: true 

discovery.zen.minimum_master_nodes: 1
discovery.zen.ping_timeout: 10s
discovery.zen.ping.unicast.hosts: ["es_master","es_slave1","es_slave2"]
